# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/ikeno/Documents/VIVADO/vga_test/vga_test.cache/wt [current_project]
set_property parent.project_path C:/Users/ikeno/Documents/VIVADO/vga_test/vga_test.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo-z7-20:part0:1.0 [current_project]
set_property ip_repo_paths c:/Xilinx/Vivado/2016.4/data/sysgen/hwcosim_ip_repos/common/packet_processor/ip/blk_mem_gen_0 [current_project]
set_property ip_output_repo c:/Users/ikeno/Documents/VIVADO/vga_test/vga_test.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/ikeno/Documents/VIVADO/vga_test/vga_test.srcs/sources_1/new/VGA_test.v
  C:/Users/ikeno/Documents/VIVADO/vga_test/vga_test.srcs/sources_1/new/top.v
}
read_ip -quiet C:/Users/ikeno/Documents/VIVADO/vga_test/vga_test.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all c:/Users/ikeno/Documents/VIVADO/vga_test/vga_test.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ikeno/Documents/VIVADO/vga_test/vga_test.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ikeno/Documents/VIVADO/vga_test/vga_test.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]
set_property is_locked true [get_files C:/Users/ikeno/Documents/VIVADO/vga_test/vga_test.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/ikeno/Documents/VIVADO/vga_test/vga_test.srcs/constrs_1/new/vga.xdc
set_property used_in_implementation false [get_files C:/Users/ikeno/Documents/VIVADO/vga_test/vga_test.srcs/constrs_1/new/vga.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top top -part xc7z020clg400-1


write_checkpoint -force -noxdef top.dcp

catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
